import Head from 'next/head'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Nextjs App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Hello, <a href="https://www.cyclic.sh/">Cyclic</a> with <a href="https://nextjs.org">Next.js!</a>
        </h1>
      </main>
      <footer className={styles.footer}>
        <a
          href="https://app.cyclic.sh"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            Cyclic
          </span>
        </a>
      </footer>
    </div>
  )
}
